import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <script src="https://kit.fontawesome.com/1b641f06db.js" crossorigin="anonymous"></script>


      </Head>

      <main className={styles.main}>
        <div className={styles.loginBox}>
          <h1>SEB ADMIN PANEL</h1>
          <form>
            <div className={styles.inputContainer}>
              <i class="fa-solid fa-envelope"></i>
              <input type="text" name="email" placeholder="Enter Your Email" required/>
            </div>
            <div className={styles.inputContainer}>
              <i class="fa-solid fa-key"></i>
              <input type="password" name="password" placeholder="Password" required/>
            </div>
            <button>Login</button>
          </form>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
